### ISSUE TITLE
XPTY0004 issue with xq-promise 0.8.0 beta

### ISSUE THREAD

**Issue by apb2006** [james-jw/xq-promise#7]
Hi James,
I am trying this with BaseX 8.4 beta 165f5fd

```
import module namespace promise = 'org.jw.basex.async.xq-promise';
let $work := http:send-request(<http:request method="GET" />, ?)
let $extract-doc := function ($res) { $res[2] }
let $extract-links := function ($res) { $res//a[@href => matches('^http')] }
let $promises :=
  for $uri in ((1 to 5) !  ('http://www.google.com', 'http://www.yahoo.com', 'http://www.amazon.com', 'http://cnn.com', 'http://www.msnbc.com'))
  let $defer := promise:defer($work, $uri, map {
       'then': ($extract-doc),
       'done': trace(?, 'Results found: ')})
  return 
     promise:attach($defer, map {'then': $extract-links })
return 
promise:fork-join($promises,1)
```

I get the error:

```
[XPTY0004] XqPromise:forkJoin(item()+, xs:integer): org.basex.query.QueryContext.<init>(Lorg/basex/query/QueryContext;Z)V.
```

Should this work?

**Comment by james-jw** [comment]
Sorry about that... The build that was in there required the custom 8.4 build I have in the lib folder. I was testing a small change to BaseX's QueryContext constructor.

Anyway, I just fixed this. I renamed the build with the custom dependency as `experimental`. 
The regular one is 0.8.0-Beta and should work with the standard BaseX build.

Also, the error handling requires an xquery module ``xq-promise.xqm'`.  Make sure that is installed. I have fixed the example and install Readme.

With this new module, the namespace has changed to:
`https://github.com/james-jw/xq-promise`

Here is an updated example. It also includes an additional fail error handler since several of these sites seem to fail the parsing stage in BaseX now. Without the error handler, the errors go uncaught and the query terminates. This is honestly a bad example, ill find some better addresses to use.

``` xquery
import module namespace promise = 'https://github.com/james-jw/xq-promise';
let $work := http:send-request(<http:request method="GET" />, ?)
let $extract-doc := function ($res) { $res[2] }
let $extract-links := function ($res) { $res//*:a[@href => matches('^http')] }
let $promises :=
  for $uri in ((1) ! ( 'http://www.yahoo.com', 'http://www.amazon.com', 'http://cnn.com', 'http://www.msnbc.com'))
  let $defer := promise:defer($work, $uri, map {
       'then': ($extract-doc),
       'done': trace(?, 'Results found: ')})
  return 
     promise:attach($defer, map {'then': $extract-links })
       => promise:fail(trace(?))
return 
$promises ! .()
```

**Comment by apb2006** [comment]
Thanks. That works for me. 
Do you intend to use [EXPath packaging](http://docs.basex.org/wiki/Repository#EXPath_Packaging) at some point? I find it easier to keep track of. It seems like your installation requirements are very similar to https://github.com/Quodatum/async#install - An XQuery and a jar.

**Comment by james-jw** [comment]
I haven't tried EXPath packaging but I should! Ill add that as a enhancement issue! Thanks for the help in testing!
